### ISSUE TITLE
pip.conf is not removed upon uninstalling nvidia-pyindex

### ISSUE THREAD

**Issue by lmmx** [NVIDIA/tensorflow#19]
Hey there, was very grateful to this package when trying to install a tricky CUDA/PyTorch/TensorFlow combo the other day, however the past few days since then I've noticed that all my pip installs were going slowly.

It turned out that the cause was the `pip.conf` file, whose header comment notes:

```py
# This file has been autogenerated or modified by NVIDIA PyIndex.
```

and which further down includes

```py
no-cache-dir = true
```

This was the cause of my slow installation (not caching any package binaries), and importantly this persisted even after removing all copies of `nvidia-pyindex` from all my conda environments.

I don't know if you'd agree but I see this as a bug: leaving `pip.conf` on a system, which then modifies the caching behaviour, is regrettable.

I thought I should open an issue to make the suggestion of removing it upon uninstallation (I'm not sure if it's possible to "clean up" after a package, but perhaps you know).

Anyway, thanks again, and of course it is at your discretion to change this or not, just wanted to bring to your attention! :+1:

**Comment by DEKHTIARJonathan** [comment]
Hi @lmmx,
First of all thanks for your comments. I'm happy that our work is useful to you.

So a few points, I'm gonna invest some time looking into it, though it seems that I won't be able to remove `no-cache-dir = true`. Namely because it would cache nvidia-pyindex which would break the mechanism. I might have an idea, I'll give it a look and keep you posted.

For the other part
> I thought I should open an issue to make the suggestion of removing it upon uninstallation (I'm not sure if it's possible to "clean up" after a package, but perhaps you know).

I totally 1000% agree. And I tried any possible way for it. Unfortunately there's no way to have a "hook" or a script to execute on pip package uninstall automatically.

There is an undocumented feature that you can trigger manually doing exactly what you are asking for: `nvidia_pyindex uninstall`.
It doesn't uninstall the pip package. It removes and clean up the changes

**Comment by lmmx** [comment]
Aha, that sounds useful! I removed them all across my system now, but if/when I reinstall I'll just use that then. I'll leave this for you to close in case you want to look into it any more. Cheers :smiley:

**Comment by DEKHTIARJonathan** [comment]
yeah so unfortunately ... Won't be able to remove `no-cache-dir = true`. Either we have it or we don't. I can't refine ...
Though, without giving up too much, we are working on something to simplify the process (and eventually get rid of `nvidia-pyindex`) so stay tuned ;) Can't give you an ETA. But hopefully some time this year. Feel free to close the issue, I don't really see any way I can fix any of the aforementioned issues (kind of by design).

**Comment by DEKHTIARJonathan** [comment]
@lmmx FYI I release a small bugfix for the uninstall command inspired by your comment ;) So now you should be able to use `nvidia-pyindex==1.0.7`

**Comment by lmmx** [comment]
Ooh exciting, good luck with this mysterious new development, I’ll keep my eyes peeled! 🦉
