### ISSUE TITLE
Do we have release that support CUDA10?

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/tensorflow#27]
For example, version 20.03? Looks older version cannot be pip installed. I don't find their source branchs neither.

**Comment by DEKHTIARJonathan** [comment]
Unfortunately the oldest PIP package we shipped was 20.06 and it came with CUDA 11

**Comment by donglinz** [comment]
@DEKHTIARJonathan Okay, so do we have a source branch that I can build from?

**Comment by DEKHTIARJonathan** [comment]
I would try to build the default branch: https://github.com/NVIDIA/tensorflow/tree/r1.15.5+nv21.05
Though I can't guarantee you that it will work.

If you need CUDA 10, did you try using the official Tensorflow Python Package ? A good part of the reason why NVIDIA maintains this repository is because Google doesn't support CUDA 11 for TensorFlow 1.x.

**Comment by donglinz** [comment]
Ah I see. Actually I am looking for TF that support both CUDA10 and AMP (using TF_ENABLE_AUTO_MIXED_PRECISION environment variable, which is a nice feature that do not need source code change). TF source code from Google's branch does not support enabling AMP through environment variable.

**Comment by donglinz** [comment]
Let me try build from the default branch. Thanks!

**Comment by DEKHTIARJonathan** [comment]
In case that helps you can always look at the 20.03 TF Container. Comes with Python 3.6 and NVIDIA CUDA 10.2.89.
It the last release of TF1 we did with CUDA 10: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_20-03.html

```bash
docker pull nvcr.io/nvidia/tensorflow:20.03-tf1-py3
```
